image:
  name: fukamachi/sbcl:2.0.9-debian
  entrypoint: [""]

pages:
  script:
    - apt-get update
    - apt-get install rsync
    - ros install coleslaw-cli
    - coleslaw stage
  artifacts:
    paths:
      - public
